server:
  port: 8080
  
spring:
  datasource:
    url: ${DB-URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 3000
      maximum-pool-size: 10
      max-lifetime: 30000

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  jackson:
    property-naming-strategy: SNAKE_CASE

auth:
  jwt:
    secret: ${SECRET_KEY}
    access_exp: ${ACCESS_EXP}
    refresh_exp: ${REFRESH_EXP}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
